import './globals.css';
import Nav from './nav';
import Footer from './footer';
import Bootstrap from './components/Bootstrap';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  };

const Layout = ({ children }) => {
  return (
    <>
      <Nav />
      <Bootstrap />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;